### ISSUE TITLE
Cannot read property 'new' of undefined

### ISSUE THREAD

**Issue by ghost** [bbrookfield/alexa-thermostat#2]
**Getting Started with Server**
1. Clone the app git clone https://github.com/bbrookfield/node-alexa-server
2. Install modules npm install
3. Run the application PORT=9000 node app.js
4. If no errors occur then you can begin adding modules or create your own module

I'm trying to run the application after cloning and I'm getting an error:

```
{}
{ service: 'sample' }
Unhandled rejection TypeError: Cannot read property 'new' of undefined
    at new alexa.request (C:\Users\shawns\Desktop\node-alexa-server\node_modules\alexa-app\index.js:92:26)
    at C:\Users\shawns\Desktop\node-alexa-server\node_modules\alexa-app\index.js:165:18
    at tryCatcher (C:\Users\shawns\Desktop\node-alexa-server\node_modules\alexa-app\node_modules\bluebird\js\main\util.j
s:26:23)
    at Promise._resolveFromResolver (C:\Users\shawns\Desktop\node-alexa-server\node_modules\alexa-app\node_modules\blueb
ird\js\main\promise.js:480:31)
    at new Promise (C:\Users\shawns\Desktop\node-alexa-server\node_modules\alexa-app\node_modules\bluebird\js\main\promi
se.js:70:37)
    at request (C:\Users\shawns\Desktop\node-alexa-server\node_modules\alexa-app\index.js:164:10)
    at C:\Users\shawns\Desktop\node-alexa-server\app.js:40:32
    at Layer.handle [as handle_request] (C:\Users\shawns\Desktop\node-alexa-server\node_modules\express\lib\router\layer
.js:95:5)
    at next (C:\Users\shawns\Desktop\node-alexa-server\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\shawns\Desktop\node-alexa-server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\shawns\Desktop\node-alexa-server\node_modules\express\lib\router\layer
.js:95:5)
    at C:\Users\shawns\Desktop\node-alexa-server\node_modules\express\lib\router\index.js:277:22
    at param (C:\Users\shawns\Desktop\node-alexa-server\node_modules\express\lib\router\index.js:349:14)
    at param (C:\Users\shawns\Desktop\node-alexa-server\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\shawns\Desktop\node-alexa-server\node_modules\express\lib\router\index.js:410:3
)
    at next (C:\Users\shawns\Desktop\node-alexa-server\node_modules\express\lib\router\index.js:271:10)
```

Windows doesn't like the PORT=9000 assignment so I'm changing it inside app.js to `app.listen(9000);`.

**Comment by ghost** [comment]
I didn't specify the correct body type in Postman. Sorry.
